### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by parasyte** [silvanshade/moveref#1]
This crate looks like it could be useful for embedded devices. The published version has poor documentation. Docs were improved recently, and it looks like some other changes were made that could be published as a new version.

Is there a milestone target for publishing the next release?

----

I could pin the crate with a git-rev, but I would prefer to manage my dependencies with `cargo update` (and other similar tools like `cargo-outdated`).

**Comment by silvanshade** [comment]
I thought I actually published the new version but apparently forgot. Thanks for the reminder. Should be updated now.
